package com.example.ui

import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.example.data.CodeProject
import com.example.data.ProjectRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch

class CodeGramViewModel(private val repository: ProjectRepository) : ViewModel() {

    val uiState: StateFlow<List<CodeProject>> = repository.allProjects
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(5000),
            initialValue = emptyList()
        )

    fun createNewProject(name: String, author: String, description: String, avatarUrl: String?, callback: (Int) -> Unit) {
        viewModelScope.launch {
            val templateCode = """
                from typing import Any, List
                from base_plugin import BasePlugin, HookResult, HookStrategy
                
                __id__ = "my_plugin_${System.currentTimeMillis()}"
                __name__ = "$name"
                __description__ = "$description"
                __author__ = "$author"
                __version__ = "1.0.0"
                
                class MyPlugin(BasePlugin):
                    def on_plugin_load(self):
                        pass
                
                    def pre_request_hook(self, request_name: str, account: int, request: Any) -> HookResult:
                        return HookResult(strategy=HookStrategy.DEFAULT)
            """.trimIndent()
            val project = CodeProject(name = name, author = author, description = description, avatarUrl = avatarUrl, pluginCode = templateCode)
            val newId = repository.insert(project)
            callback(newId)
        }
    }

    fun deleteProject(id: Int) {
        viewModelScope.launch {
            repository.deleteById(id)
        }
    }

    fun generateProjectWithGemini(apiKey: String, prompt: String, author: String, callback: (Int) -> Unit, onError: (String) -> Unit) {
        if (apiKey.isEmpty()) {
            onError("API ключ Gemini не установлен")
            return
        }
        viewModelScope.launch {
            try {
                val sysPrompt = "You are an assistant for writing ExtraGram Python plugins. Based on the user's request, write the python plugin code. Make sure your response starts exactly with the code (no markdown or language tag like ```python). The class must inherit BasePlugin."
                val codeResponse = com.example.data.GeminiHelper.complete(apiKey, "$sysPrompt\nUser request: $prompt")
                
                val cleanedCode = codeResponse.replace("```python", "").replace("```", "").trim()
                
                val nameMatch = Regex("""__name__\s*=\s*['"](.*?)['"]""").find(cleanedCode)
                val descMatch = Regex("""__description__\s*=\s*['"](.*?)['"]""").find(cleanedCode)
                
                val finalName = nameMatch?.groupValues?.get(1) ?: "AI Generated"
                val finalDesc = descMatch?.groupValues?.get(1) ?: "Generated by Gemini"
                
                // Add the __author__ injection if lacking
                val finalCode = if (cleanedCode.contains("__author__")) cleanedCode else """
                    __author__ = "$author"
                    
$cleanedCode
                """.trimIndent()
                
                val project = CodeProject(
                    name = finalName,
                    author = author,
                    description = finalDesc,
                    avatarUrl = null,
                    pluginCode = finalCode
                )
                val newId = repository.insert(project)
                callback(newId)
            } catch (e: Exception) {
                onError("Ошибка генерации: ${e.message}")
            }
        }
    }
}

class CodeGramViewModelFactory(private val repository: ProjectRepository) : ViewModelProvider.Factory {
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        if (modelClass.isAssignableFrom(CodeGramViewModel::class.java)) {
            @Suppress("UNCHECKED_CAST")
            return CodeGramViewModel(repository) as T
        }
        throw IllegalArgumentException("Unknown ViewModel class")
    }
}
